Add cista::*::cstring type
felixguendling/cista pull request #202
Opened 2023-10-29 02:41 UTC by khng300

This new type is able to store a trailing \0 character, without compromising one byte for storage when the string is a small-string.

Storage of NUL character within data is also supported.

This is inspired by
https://github.com/felixguendling/cista/issues/187#issuecomment-1603128882.

See https://github.com/felixguendling/cista/issues/187.

2023-10-29 21:41 UTC, felixguendling commented
Thank you for your PR! I think some tests would be useful, formatting should be fixed (using clang-format), and maybe a bit of description in the code how it works could help me to understand what's going on (just the tricky spots where the magic happens).

2023-11-15 13:15 UTC, felixguendling requested changes
Looks great! I guess some tests for serialization and deserialization would be nice :)

2023-11-24 09:53 UTC, felixguendling approved these changes

2023-11-24 09:53 UTC, felixguendling commented
Still in draft mode. Something missing?

2023-11-25 05:53 UTC, khng300 commented
I was considering if it is still worth keeping cstring_view in such case. If not, the corner case of checking null can be omitted.

2023-11-25 06:21 UTC, khng300 commented
> Still in draft mode. Something missing?

The latest commit just pull out the null-pointer checks for set_owning related calls().

2023-11-25 07:03 UTC, khng300 commented
* Guard against the case of nullptr with non-zero length.

2023-11-25 15:01 UTC, merged

2023-11-25 15:01 UTC, felixguendling commented
Thank you!